interface GoodsMapping {
  term: string;
  class: number;
  description: string;
}

// Common goods and services mapped to their Nice classes
export const goodsServicesMapping: GoodsMapping[] = [
  // Class 1 - Chemicals
  { term: 'acetone', class: 1, description: 'Industrial chemicals' },
  { term: 'acrylic resins', class: 1, description: 'Unprocessed artificial resins' },
  { term: 'activated carbon', class: 1, description: 'Filtering materials' },
  { term: 'adhesives for industrial use', class: 1, description: 'Industrial adhesives' },
  { term: 'agricultural chemicals', class: 1, description: 'Chemical preparations for agriculture' },
  { term: 'alcohol', class: 1, description: 'Industrial chemicals' },
  { term: 'ammonia', class: 1, description: 'Industrial chemicals' },
  { term: 'antifreeze', class: 1, description: 'Automotive chemicals' },
  { term: 'artificial sweeteners', class: 1, description: 'Chemical sweeteners' },
  { term: 'benzene', class: 1, description: 'Industrial chemicals' },
  { term: 'biochemical catalysts', class: 1, description: 'Chemical catalysts' },
  { term: 'brake fluid', class: 1, description: 'Automotive chemicals' },
  { term: 'calcium carbonate', class: 1, description: 'Industrial chemicals' },
  { term: 'carbon dioxide', class: 1, description: 'Industrial gases' },
  { term: 'catalysts', class: 1, description: 'Chemical catalysts' },
  { term: 'caustic soda', class: 1, description: 'Industrial chemicals' },
  { term: 'cellulose', class: 1, description: 'Raw material chemicals' },
  { term: 'cement preservatives', class: 1, description: 'Construction chemicals' },
  { term: 'ceramic glazings', class: 1, description: 'Industrial chemicals' },
  { term: 'chemical additives', class: 1, description: 'Industrial additives' },
  { term: 'chemical condensation preparations', class: 1, description: 'Industrial chemicals' },
  { term: 'chemical intensifiers for paper', class: 1, description: 'Paper industry chemicals' },
  { term: 'chemical preservatives', class: 1, description: 'Preservative chemicals' },
  { term: 'chemical reagents', class: 1, description: 'Laboratory chemicals' },
  { term: 'chemical substances for preserving foodstuffs', class: 1, description: 'Food preservatives' },
  { term: 'chemicals for forestry', class: 1, description: 'Forestry chemicals' },
  { term: 'chemicals for photography', class: 1, description: 'Photographic chemicals' },
  { term: 'chemicals for treating water', class: 1, description: 'Water treatment chemicals' },
  { term: 'chlorine', class: 1, description: 'Industrial chemicals' },
  { term: 'citric acid', class: 1, description: 'Industrial chemicals' },
  { term: 'color brightening chemicals', class: 1, description: 'Textile industry chemicals' },
  { term: 'compost', class: 1, description: 'Fertilizers' },
  { term: 'coolants', class: 1, description: 'Industrial coolants' },
  { term: 'copper sulfate', class: 1, description: 'Industrial chemicals' },
  { term: 'curing preparations', class: 1, description: 'Industrial chemicals' },
  { term: 'defoliants', class: 1, description: 'Agricultural chemicals' },
  { term: 'degreasing preparations', class: 1, description: 'Industrial solvents' },
  { term: 'detergent additives', class: 1, description: 'Chemical additives' },
  { term: 'diagnostic preparations', class: 1, description: 'Laboratory chemicals' },
  { term: 'distilled water', class: 1, description: 'Chemical preparations' },
  { term: 'dry ice', class: 1, description: 'Refrigerants' },
  { term: 'emulsifiers', class: 1, description: 'Industrial chemicals' },
  { term: 'enzyme preparations', class: 1, description: 'Industrial enzymes' },
  { term: 'epoxy resins', class: 1, description: 'Unprocessed resins' },
  { term: 'fertilizers', class: 1, description: 'Agricultural chemicals' },
  { term: 'filtering materials', class: 1, description: 'Chemical preparations' },
  { term: 'fire extinguishing compositions', class: 1, description: 'Safety chemicals' },
  { term: 'fireproofing preparations', class: 1, description: 'Protective chemicals' },
  { term: 'flocculants', class: 1, description: 'Water treatment chemicals' },
  { term: 'fluorine', class: 1, description: 'Industrial chemicals' },
  { term: 'foundry binding substances', class: 1, description: 'Industrial chemicals' },
  { term: 'galvanizing preparations', class: 1, description: 'Metal treatment chemicals' },
  { term: 'getters', class: 1, description: 'Industrial chemicals' },
  { term: 'glass-frosting chemicals', class: 1, description: 'Glass industry chemicals' },
  { term: 'glycerine', class: 1, description: 'Industrial chemicals' },
  { term: 'graphite', class: 1, description: 'Industrial chemicals' },
  { term: 'growth regulating preparations', class: 1, description: 'Agricultural chemicals' },
  { term: 'gum solvents', class: 1, description: 'Industrial solvents' },
  { term: 'helium', class: 1, description: 'Industrial gases' },
  { term: 'horticultural chemicals', class: 1, description: 'Agricultural chemicals' },
  { term: 'hydraulic fluids', class: 1, description: 'Industrial fluids' },
  { term: 'hydrogen', class: 1, description: 'Industrial gases' },
  { term: 'hydrogen peroxide', class: 1, description: 'Industrial chemicals' },
  { term: 'industrial gases', class: 1, description: 'Chemical preparations' },
  { term: 'iodine', class: 1, description: 'Industrial chemicals' },
  { term: 'ion exchangers', class: 1, description: 'Chemical compounds' },
  { term: 'iron salts', class: 1, description: 'Industrial chemicals' },
  { term: 'ketones', class: 1, description: 'Industrial chemicals' },
  { term: 'lactic acid', class: 1, description: 'Industrial chemicals' },
  { term: 'lamp black', class: 1, description: 'Industrial chemicals' },
  { term: 'leather treatment chemicals', class: 1, description: 'Industrial chemicals' },
  { term: 'leather-waterproofing chemicals', class: 1, description: 'Protective chemicals' },
  { term: 'lecithin', class: 1, description: 'Industrial chemicals' },
  { term: 'lime acetate', class: 1, description: 'Industrial chemicals' },
  { term: 'lime carbonate', class: 1, description: 'Industrial chemicals' },
  { term: 'lime chloride', class: 1, description: 'Industrial chemicals' },
  { term: 'lithium', class: 1, description: 'Industrial chemicals' },
  { term: 'magnesium carbonate', class: 1, description: 'Industrial chemicals' },
  { term: 'mangrove bark', class: 1, description: 'Industrial chemicals' },
  { term: 'masonry preservatives', class: 1, description: 'Construction chemicals' },
  { term: 'metal annealing preparations', class: 1, description: 'Metal treatment chemicals' },
  { term: 'metal hardening preparations', class: 1, description: 'Metal treatment chemicals' },
  { term: 'metal tempering preparations', class: 1, description: 'Metal treatment chemicals' },
  { term: 'metalloids', class: 1, description: 'Industrial chemicals' },
  { term: 'methyl benzene', class: 1, description: 'Industrial chemicals' },
  { term: 'milk ferments', class: 1, description: 'Chemical preparations' },
  { term: 'mineral acids', class: 1, description: 'Industrial chemicals' },
  { term: 'mold release preparations', class: 1, description: 'Industrial chemicals' },
  { term: 'mold-release compounds', class: 1, description: 'Industrial chemicals' },
  { term: 'mordants', class: 1, description: 'Industrial chemicals' },
  { term: 'naphthalene', class: 1, description: 'Industrial chemicals' },
  { term: 'nitrates', class: 1, description: 'Industrial chemicals' },
  { term: 'nitrogen', class: 1, description: 'Industrial gases' },
  { term: 'oil dispersants', class: 1, description: 'Industrial chemicals' },
  { term: 'oil-purifying chemicals', class: 1, description: 'Industrial chemicals' },
  { term: 'oxygen', class: 1, description: 'Industrial gases' },
  { term: 'paper pulp', class: 1, description: 'Raw materials' },
  { term: 'peat', class: 1, description: 'Fertilizers' },
  { term: 'pectin', class: 1, description: 'Industrial chemicals' },
  { term: 'photographic developers', class: 1, description: 'Photographic chemicals' },
  { term: 'photographic emulsions', class: 1, description: 'Photographic chemicals' },
  { term: 'plasticizers', class: 1, description: 'Industrial chemicals' },
  { term: 'plutonium', class: 1, description: 'Industrial chemicals' },
  { term: 'potash', class: 1, description: 'Industrial chemicals' },
  { term: 'praseodymium', class: 1, description: 'Industrial chemicals' },
  { term: 'radiator flushing chemicals', class: 1, description: 'Automotive chemicals' },
  { term: 'rare earth metals', class: 1, description: 'Industrial chemicals' },
  { term: 'reducing agents', class: 1, description: 'Chemical agents' },
  { term: 'refrigerants', class: 1, description: 'Industrial chemicals' },
  { term: 'antifreeze', class: 1, description: 'Automotive chemicals' },
  { term: 'brake fluid', class: 1, description: 'Automotive chemicals' },
  { term: 'car engine coolant', class: 1, description: 'Automotive chemicals' },
  { term: 'chemical additives for fuel', class: 1, description: 'Automotive chemicals' },
  { term: 'chemical additives for oil', class: 1, description: 'Automotive chemicals' },
  { term: 'chemical preparations for decarbonizing engines', class: 1, description: 'Automotive chemicals' },
  { term: 'chemical sealants for auto bodies', class: 1, description: 'Automotive chemicals' },
  { term: 'engine degreasing chemicals', class: 1, description: 'Automotive chemicals' },
  { term: 'fuel injection cleaner chemical additives', class: 1, description: 'Automotive chemicals' },
  { term: 'power steering fluid', class: 1, description: 'Automotive chemicals' },
  { term: 'radiator additives', class: 1, description: 'Automotive chemicals' },
  { term: 'radiator flush', class: 1, description: 'Automotive chemicals' },
  { term: 'transmission fluid', class: 1, description: 'Automotive chemicals' },
  { term: 'windshield washer fluid', class: 1, description: 'Automotive chemicals' },
  
  // Class 2 - Paints and Coatings
  { term: 'acrylic paint', class: 2, description: 'Paints and coatings' },
  { term: 'aerosol paint', class: 2, description: 'Spray paints' },
  { term: 'aluminum paint', class: 2, description: 'Metal paints' },
  { term: 'anti-corrosive bands', class: 2, description: 'Protective coatings' },
  { term: 'anti-corrosive preparations', class: 2, description: 'Protective coatings' },
  { term: 'anti-fouling paint', class: 2, description: 'Marine paints' },
  { term: 'anti-graffiti coatings', class: 2, description: 'Protective coatings' },
  { term: 'anti-rust greases', class: 2, description: 'Protective preparations' },
  { term: 'anti-rust oils', class: 2, description: 'Protective preparations' },
  { term: 'anti-rust preparations', class: 2, description: 'Protective coatings' },
  { term: 'anti-tarnishing preparations', class: 2, description: 'Metal protection' },
  { term: 'artists paints', class: 2, description: 'Art supplies' },
  { term: 'asbestos paints', class: 2, description: 'Industrial paints' },
  { term: 'automotive clear coat', class: 2, description: 'Automotive coatings' },
  { term: 'automotive paint primer', class: 2, description: 'Automotive coatings' },
  { term: 'automotive paint sealant', class: 2, description: 'Automotive coatings' },
  { term: 'automotive touch-up paint', class: 2, description: 'Automotive coatings' },
  { term: 'automotive touch-up paint', class: 2, description: 'Automotive coatings' },
  { term: 'car paint protection film', class: 2, description: 'Automotive coatings' },
  { term: 'ceramic coating for cars', class: 2, description: 'Automotive coatings' },
  { term: 'ceramic paints', class: 2, description: 'Specialty coatings' },
  { term: 'coatings for roofing felt', class: 2, description: 'Construction coatings' },
  { term: 'coatings for wood', class: 2, description: 'Wood finishes' },
  { term: 'cobalt oxide', class: 2, description: 'Paint pigments' },
  { term: 'colorants', class: 2, description: 'Paint additives' },
  { term: 'copal', class: 2, description: 'Natural resins' },
  { term: 'copal varnish', class: 2, description: 'Wood finishes' },
  { term: 'creosote for wood preservation', class: 2, description: 'Wood preservatives' },
  { term: 'distempers', class: 2, description: 'Water-based paints' },
  { term: 'dyes', class: 2, description: 'Colorants' },
  { term: 'enamels', class: 2, description: 'Paint finishes' },
  { term: 'enamels for painting', class: 2, description: 'Paint finishes' },
  { term: 'epoxy coatings', class: 2, description: 'Industrial coatings' },
  { term: 'exterior paints', class: 2, description: 'Outdoor paints' },
  { term: 'fireproof paints', class: 2, description: 'Protective coatings' },
  { term: 'fixatives for watercolors', class: 2, description: 'Art supplies' },
  { term: 'floor protection varnishes', class: 2, description: 'Floor coatings' },
  { term: 'fluorescent paints', class: 2, description: 'Specialty paints' },
  { term: 'foil for painters', class: 2, description: 'Decorative materials' },
  { term: 'food coloring', class: 2, description: 'Food dyes' },
  { term: 'gamboge for painting', class: 2, description: 'Natural pigments' },
  { term: 'glazes', class: 2, description: 'Paint finishes' },
  { term: 'gum resins', class: 2, description: 'Natural resins' },
  { term: 'gum-lac', class: 2, description: 'Natural resins' },
  { term: 'indigo', class: 2, description: 'Natural pigments' },
  { term: 'ink for leather', class: 2, description: 'Leather dyes' },
  { term: 'ink for skin-dressing', class: 2, description: 'Leather dyes' },
  { term: 'interior paints', class: 2, description: 'Indoor paints' },
  { term: 'lacquers', class: 2, description: 'Paint finishes' },
  { term: 'lamp black', class: 2, description: 'Paint pigments' },
  { term: 'lime wash', class: 2, description: 'Wall coatings' },
  { term: 'marking ink for animals', class: 2, description: 'Specialty inks' },
  { term: 'mastic', class: 2, description: 'Sealants' },
  { term: 'metal foil for painters', class: 2, description: 'Decorative materials' },
  { term: 'metal powders for painting', class: 2, description: 'Paint pigments' },
  { term: 'mordants', class: 2, description: 'Wood stains' },
  { term: 'natural resins', class: 2, description: 'Raw materials' },
  { term: 'oil colors', class: 2, description: 'Artist supplies' },
  { term: 'oil paints', class: 2, description: 'Artist supplies' },
  { term: 'oils for wood preservation', class: 2, description: 'Wood preservatives' },
  { term: 'paint primers', class: 2, description: 'Paint preparations' },
  { term: 'paint sealers', class: 2, description: 'Paint preparations' },
  { term: 'paint thinners', class: 2, description: 'Paint preparations' },
  { term: 'paper for dyeing Easter eggs', class: 2, description: 'Specialty dyes' },
  { term: 'pigments', class: 2, description: 'Paint materials' },
  { term: 'powder coatings', class: 2, description: 'Industrial coatings' },
  { term: 'primers', class: 2, description: 'Paint preparations' },
  { term: 'printing ink', class: 2, description: 'Printing materials' },
  { term: 'protective coatings', class: 2, description: 'Industrial coatings' },
  { term: 'protective preparations for metals', class: 2, description: 'Metal coatings' },
  { term: 'raw natural resins', class: 2, description: 'Paint materials' },
  { term: 'red lead', class: 2, description: 'Paint pigments' },
  { term: 'rust preventatives', class: 2, description: 'Protective coatings' },
  { term: 'saffron', class: 2, description: 'Natural colorants' },
  { term: 'sandarac', class: 2, description: 'Natural resins' },
  { term: 'shellac', class: 2, description: 'Wood finishes' },
  { term: 'shoe dyes', class: 2, description: 'Leather dyes' },
  { term: 'siccatives', class: 2, description: 'Paint driers' },
  { term: 'silver emulsions', class: 2, description: 'Paint pigments' },
  { term: 'silver paste', class: 2, description: 'Paint pigments' },
  { term: 'silvering powders', class: 2, description: 'Paint pigments' },
  { term: 'stains for leather', class: 2, description: 'Leather dyes' },
  { term: 'sumac for varnishes', class: 2, description: 'Natural resins' },
  { term: 'synthetic resin paints', class: 2, description: 'Industrial paints' },
  { term: 'tattoo ink', class: 2, description: 'Permanent inks' },
  { term: 'thickeners for paints', class: 2, description: 'Paint additives' },
  { term: 'thinners for lacquers', class: 2, description: 'Paint preparations' },
  { term: 'thinners for paints', class: 2, description: 'Paint preparations' },
  { term: 'titanium dioxide', class: 2, description: 'Paint pigments' },
  { term: 'toner cartridges', class: 2, description: 'Printing materials' },
  { term: 'turpentine', class: 2, description: 'Paint thinners' },
  { term: 'undercoating for vehicle chassis', class: 2, description: 'Vehicle coatings' },
  { term: 'varnishes', class: 2, description: 'Wood finishes' },
  { term: 'watercolor paints', class: 2, description: 'Artist supplies' },
  { term: 'waterproofing paints', class: 2, description: 'Protective coatings' },
  { term: 'white lead', class: 2, description: 'Paint pigments' },
  { term: 'wood coatings', class: 2, description: 'Wood finishes' },
  { term: 'wood mordants', class: 2, description: 'Wood stains' },
  { term: 'wood preservatives', class: 2, description: 'Wood protection' },
  { term: 'wood stains', class: 2, description: 'Wood finishes' },
  
  // Class 3 - Cosmetics and Cleaning (continued)
  { term: 'cosmetic soaps', class: 3, description: 'Cleansing products' },
  { term: 'cotton sticks for cosmetic purposes', class: 3, description: 'Beauty accessories' },
  { term: 'cotton wool for cosmetic purposes', class: 3, description: 'Beauty accessories' },
  { term: 'cuticle cream', class: 3, description: 'Nail care products' },
  { term: 'dental bleaching gels', class: 3, description: 'Oral care products' },
  { term: 'denture polishes', class: 3, description: 'Oral care products' },
  { term: 'deodorant soap', class: 3, description: 'Personal care products' },
  { term: 'depilatories', class: 3, description: 'Hair removal products' },
  { term: 'dry shampoo', class: 3, description: 'Hair care products' },
  { term: 'eau de cologne', class: 3, description: 'Fragrances' },
  { term: 'essential oils', class: 3, description: 'Aromatherapy products' },
  { term: 'eye cream', class: 3, description: 'Skin care products' },
  { term: 'eye liner', class: 3, description: 'Eye makeup' },
  { term: 'eye makeup', class: 3, description: 'Cosmetics' },
  { term: 'eye makeup remover', class: 3, description: 'Makeup removers' },
  { term: 'eye shadow', class: 3, description: 'Eye makeup' },
  { term: 'eyebrow cosmetics', class: 3, description: 'Eye makeup' },
  { term: 'eyebrow pencils', class: 3, description: 'Eye makeup' },
  { term: 'eyelash tint', class: 3, description: 'Eye makeup' },
  { term: 'face cream', class: 3, description: 'Skin care products' },
  { term: 'face masks', class: 3, description: 'Skin care products' },
  { term: 'face powder', class: 3, description: 'Makeup products' },
  { term: 'facial cleansers', class: 3, description: 'Skin care products' },
  { term: 'facial scrubs', class: 3, description: 'Skin care products' },
  { term: 'facial toners', class: 3, description: 'Skin care products' },
  { term: 'false eyelashes', class: 3, description: 'Beauty accessories' },
  { term: 'false nails', class: 3, description: 'Beauty accessories' },
  { term: 'foundation makeup', class: 3, description: 'Makeup products' },
  { term: 'fragrance', class: 3, description: 'Perfumery' },
  { term: 'glass cleaner', class: 3, description: 'Cleaning products' },
  { term: 'hair bleach', class: 3, description: 'Hair care products' },
  { term: 'hair color', class: 3, description: 'Hair care products' },
  { term: 'hair conditioner', class: 3, description: 'Hair care products' },
  { term: 'hair cream', class: 3, description: 'Hair care products' },
  { term: 'hair dye', class: 3, description: 'Hair care products' },
  { term: 'hair gel', class: 3, description: 'Hair styling products' },
  { term: 'hair mousse', class: 3, description: 'Hair styling products' },
  { term: 'hair oil', class: 3, description: 'Hair care products' },
  { term: 'hair pomade', class: 3, description: 'Hair styling products' },
  { term: 'hair spray', class: 3, description: 'Hair styling products' },
  { term: 'hair straightening preparations', class: 3, description: 'Hair styling products' },
  { term: 'hair wax', class: 3, description: 'Hair styling products' },
  { term: 'hand cream', class: 3, description: 'Skin care products' },
  { term: 'hand soap', class: 3, description: 'Cleansing products' },
  { term: 'henna', class: 3, description: 'Hair dyes' },
  { term: 'household cleaners', class: 3, description: 'Cleaning products' },
  { term: 'incense', class: 3, description: 'Air fresheners' },
  { term: 'jasmine oil', class: 3, description: 'Essential oils' },
  { term: 'laundry bleach', class: 3, description: 'Cleaning products' },
  { term: 'laundry detergent', class: 3, description: 'Cleaning products' },
  { term: 'lavender oil', class: 3, description: 'Essential oils' },
  { term: 'lip balm', class: 3, description: 'Lip care products' },
  { term: 'lip gloss', class: 3, description: 'Lip makeup' },
  { term: 'lip liner', class: 3, description: 'Lip makeup' },
  { term: 'lipstick', class: 3, description: 'Lip makeup' },
  { term: 'liquid soap', class: 3, description: 'Cleansing products' },
  { term: 'makeup', class: 3, description: 'Cosmetics' },
  { term: 'makeup remover', class: 3, description: 'Cosmetic products' },
  { term: 'mascara', class: 3, description: 'Eye makeup' },
  { term: 'massage gels', class: 3, description: 'Body care products' },
  { term: 'massage oils', class: 3, description: 'Body care products' },
  { term: 'mouthwash', class: 3, description: 'Oral care products' },
  { term: 'nail art stickers', class: 3, description: 'Nail care products' },
  { term: 'nail care preparations', class: 3, description: 'Nail care products' },
  { term: 'nail polish', class: 3, description: 'Nail care products' },
  { term: 'nail polish remover', class: 3, description: 'Nail care products' },
  { term: 'night cream', class: 3, description: 'Skin care products' },
  { term: 'non-medicated skin care preparations', class: 3, description: 'Skin care products' },
  { term: 'oils for cosmetic purposes', class: 3, description: 'Cosmetic products' },
  { term: 'oven cleaner', class: 3, description: 'Cleaning products' },
  { term: 'perfumes', class: 3, description: 'Fragrances' },
  { term: 'peppermint breath fresheners', class: 3, description: 'Oral care products' },
  { term: 'permanent wave preparations', class: 3, description: 'Hair styling products' },
  { term: 'petroleum jelly for cosmetic purposes', class: 3, description: 'Skin care products' },
  { term: 'potpourri', class: 3, description: 'Air fresheners' },
  { term: 'powder for makeup', class: 3, description: 'Makeup products' },
  { term: 'pre-moistened cosmetic wipes', class: 3, description: 'Cleansing products' },
  { term: 'pumice stone', class: 3, description: 'Body care products' },
  { term: 'rose oil', class: 3, description: 'Essential oils' },
  { term: 'sachets for perfuming linen', class: 3, description: 'Air fresheners' },
  { term: 'scented water', class: 3, description: 'Fragrances' },
  { term: 'shampoo', class: 3, description: 'Hair care products' },
  { term: 'shaving cream', class: 3, description: 'Shaving products' },
  { term: 'shaving foam', class: 3, description: 'Shaving products' },
  { term: 'shaving gel', class: 3, description: 'Shaving products' },
  { term: 'shaving preparations', class: 3, description: 'Shaving products' },
  { term: 'shower gel', class: 3, description: 'Bath preparations' },
  { term: 'skin bronzer', class: 3, description: 'Makeup products' },
  { term: 'skin cleansers', class: 3, description: 'Skin care products' },
  { term: 'skin cream', class: 3, description: 'Skin care products' },
  { term: 'skin exfoliants', class: 3, description: 'Skin care products' },
  { term: 'skin lightening creams', class: 3, description: 'Skin care products' },
  { term: 'skin moisturizer', class: 3, description: 'Skin care products' },
  { term: 'skin toners', class: 3, description: 'Skin care products' },
  { term: 'soap', class: 3, description: 'Cleansing products' },
  { term: 'stain removers', class: 3, description: 'Cleaning products' },
  { term: 'sunscreen', class: 3, description: 'Sun care products' },
  { term: 'suntan lotion', class: 3, description: 'Sun care products' },
  { term: 'talcum powder', class: 3, description: 'Body care products' },
  { term: 'teeth whitening preparations', class: 3, description: 'Oral care products' },
  { term: 'tissues impregnated with cosmetic lotions', class: 3, description: 'Cleansing products' },
  { term: 'toilet water', class: 3, description: 'Fragrances' },
  { term: 'toothpaste', class: 3, description: 'Oral care products' },
  { term: 'vaginal washes for personal sanitary purposes', class: 3, description: 'Personal care products' },
  { term: 'window cleaner', class: 3, description: 'Cleaning products' },
  
  // Class 21 - Household items
  { term: 'microfiber cloth', class: 21, description: 'Cleaning cloths and materials' },
  { term: 'cleaning cloth', class: 21, description: 'Cleaning cloths and materials' },
  { term: 'brush', class: 21, description: 'Brushes and cleaning materials' },
  { term: 'sponge', class: 21, description: 'Cleaning materials' },
  { term: 'mop', class: 21, description: 'Cleaning implements' },
  { term: 'dustpan', class: 21, description: 'Cleaning implements' },
  { term: 'broom', class: 21, description: 'Cleaning implements' },
  { term: 'bucket', class: 21, description: 'Household containers' },
  { term: 'trash can', class: 21, description: 'Household containers' },
  { term: 'dish rack', class: 21, description: 'Kitchen utensils' },
  { term: 'cutlery tray', class: 21, description: 'Kitchen utensils' },
  { term: 'plate', class: 21, description: 'Tableware' },
  { term: 'bowl', class: 21, description: 'Tableware' },
  { term: 'cup', class: 21, description: 'Drinking vessels' },
  { term: 'glass', class: 21, description: 'Drinking vessels' },
  { term: 'mug', class: 21, description: 'Drinking vessels' },
  { term: 'pot', class: 21, description: 'Cookware' },
  { term: 'pan', class: 21, description: 'Cookware' },
  { term: 'cutting board', class: 21, description: 'Kitchen utensils' },
  { term: 'colander', class: 21, description: 'Kitchen utensils' },
  { term: 'strainer', class: 21, description: 'Kitchen utensils' },
  { term: 'soap dispenser', class: 21, description: 'Bathroom accessories' },
  { term: 'toothbrush holder', class: 21, description: 'Bathroom accessories' },
  { term: 'toilet brush', class: 21, description: 'Bathroom accessories' },
  { term: 'vase', class: 21, description: 'Indoor decorative items' },
  { term: 'flower pot', class: 21, description: 'Gardening containers' },
  { term: 'watering can', class: 21, description: 'Gardening implements' },
  { term: 'car drying towel', class: 21, description: 'Car cleaning implements' },
  { term: 'car polishing cloth', class: 21, description: 'Car cleaning implements' },
  { term: 'car wash brush', class: 21, description: 'Car cleaning implements' },
  { term: 'car wash mitt', class: 21, description: 'Car cleaning implements' },
  { term: 'car wash sponge', class: 21, description: 'Car cleaning implements' },
  { term: 'car wax applicator', class: 21, description: 'Car cleaning implements' },
  { term: 'detailing brush', class: 21, description: 'Car cleaning implements' },
  { term: 'microfiber towel for cars', class: 21, description: 'Car cleaning implements' },
  { term: 'tire brush', class: 21, description: 'Car cleaning implements' },
  { term: 'wheel brush', class: 21, description: 'Car cleaning implements' },
  
  // Class 25 - Clothing
  { term: 'shirt', class: 25, description: 'Clothing' },
  { term: 'pants', class: 25, description: 'Clothing' },
  { term: 'shoes', class: 25, description: 'Footwear' },
  { term: 'hat', class: 25, description: 'Headwear' },
  { term: 'jacket', class: 25, description: 'Clothing' },
  
  // Class 9 - Electronics
  { term: 'computer', class: 9, description: 'Electronic devices' },
  { term: 'software', class: 9, description: 'Computer software' },
  { term: 'app', class: 9, description: 'Computer software' },
  { term: 'smartphone', class: 9, description: 'Electronic devices' },
  { term: 'headphones', class: 9, description: 'Audio equipment' },
  
  // Class 30 - Food items
  { term: 'coffee', class: 30, description: 'Coffee and coffee substitutes' },
  { term: 'tea', class: 30, description: 'Tea and tea substitutes' },
  { term: 'chocolate', class: 30, description: 'Confectionery' },
  { term: 'candy', class: 30, description: 'Confectionery' },
  { term: 'bread', class: 30, description: 'Bakery products' },
  
  // Class 35 - Business Services
  { term: 'advertising', class: 35, description: 'Advertising and marketing services' },
  { term: 'marketing', class: 35, description: 'Marketing services' },
  { term: 'retail', class: 35, description: 'Retail store services' },
  { term: 'consulting', class: 35, description: 'Business consulting services' },
  
  // Class 41 - Education
  { term: 'training', class: 41, description: 'Educational services' },
  { term: 'teaching', class: 41, description: 'Educational services' },
  { term: 'coaching', class: 41, description: 'Educational services' },
  { term: 'workshop', class: 41, description: 'Educational services' },
  
  // Class 42 - Technology Services
  { term: 'software development', class: 42, description: 'Software development services' },
  { term: 'web design', class: 42, description: 'Website design services' },
  { term: 'cloud computing', class: 42, description: 'Cloud computing services' },
  { term: 'hosting', class: 42, description: 'Web hosting services' },
  
  // Class 43 - Food and Drink Services
  { term: 'restaurant', class: 43, description: 'Restaurant services' },
  { term: 'cafe', class: 43, description: 'Café services' },
  { term: 'catering', class: 43, description: 'Catering services' },
  { term: 'bar', class: 43, description: 'Bar services' },
  
  // Class 44 - Medical Services
  { term: 'medical', class: 44, description: 'Medical services' },
  { term: 'dental', class: 44, description: 'Dental services' },
  { term: 'therapy', class: 44, description: 'Therapeutic services' },
  { term: 'spa', class: 44, description: 'Beauty spa services' },
  
  // Class 6 - Common Metals
  { term: 'aluminum foil', class: 6, description: 'Metal foils' },
  { term: 'aluminum wire', class: 6, description: 'Metal wires' },
  { term: 'anchor plates', class: 6, description: 'Metal fasteners' },
  { term: 'angle irons', class: 6, description: 'Metal building materials' },
  { term: 'anti-friction metal', class: 6, description: 'Metal alloys' },
  { term: 'anvils', class: 6, description: 'Metal work equipment' },
  { term: 'armor plating', class: 6, description: 'Metal protection materials' },
  { term: 'badges of metal', class: 6, description: 'Metal identification items' },
  { term: 'balls of steel', class: 6, description: 'Metal balls' },
  { term: 'bands of metal', class: 6, description: 'Metal fasteners' },
  { term: 'barbed wire', class: 6, description: 'Metal fencing materials' },
  { term: 'barrel hoops of metal', class: 6, description: 'Metal containers' },
  { term: 'bars for metal railings', class: 6, description: 'Metal building materials' },
  { term: 'baskets of metal', class: 6, description: 'Metal containers' },
  { term: 'beams of metal', class: 6, description: 'Metal building materials' },
  { term: 'bed casters of metal', class: 6, description: 'Metal furniture fittings' },
  { term: 'bells', class: 6, description: 'Metal sound devices' },
  { term: 'belt stretchers of metal', class: 6, description: 'Metal tools' },
  { term: 'bindings of metal', class: 6, description: 'Metal fasteners' },
  { term: 'bird baths of metal', class: 6, description: 'Metal outdoor items' },
  { term: 'blooms [metallurgy]', class: 6, description: 'Metal manufacturing' },
  { term: 'bolts of metal', class: 6, description: 'Metal fasteners' },
  { term: 'box fasteners of metal', class: 6, description: 'Metal fasteners' },
  { term: 'brackets of metal', class: 6, description: 'Metal building materials' },
  { term: 'branching pipes of metal', class: 6, description: 'Metal plumbing materials' },
  { term: 'brass rings', class: 6, description: 'Metal rings' },
  { term: 'brass unwrought or semi-wrought', class: 6, description: 'Metal materials' },
  { term: 'brazing alloys', class: 6, description: 'Metal alloys' },
  { term: 'bronze', class: 6, description: 'Metal materials' },
  { term: 'buckles of metal', class: 6, description: 'Metal fasteners' },
  { term: 'building panels of metal', class: 6, description: 'Metal building materials' },
  { term: 'bungs of metal', class: 6, description: 'Metal stoppers' },
  { term: 'cable joints of metal', class: 6, description: 'Metal connectors' },
  { term: 'cables of metal', class: 6, description: 'Metal cables' },
  { term: 'cadmium', class: 6, description: 'Metal materials' },
  { term: 'casement windows of metal', class: 6, description: 'Metal building materials' },
  { term: 'cash boxes of metal', class: 6, description: 'Metal containers' },
  { term: 'cast iron', class: 6, description: 'Metal materials' },
  { term: 'cast steel', class: 6, description: 'Metal materials' },
  { term: 'cattle chains', class: 6, description: 'Metal chains' },
  { term: 'ceilings of metal', class: 6, description: 'Metal building materials' },
  { term: 'chains of metal', class: 6, description: 'Metal chains' },
  { term: 'chests of metal', class: 6, description: 'Metal containers' },
  { term: 'chrome iron', class: 6, description: 'Metal alloys' },
  { term: 'chrome ores', class: 6, description: 'Metal ores' },
  { term: 'chromium', class: 6, description: 'Metal materials' },
  { term: 'cladding of metal', class: 6, description: 'Metal building materials' },
  { term: 'clips of metal', class: 6, description: 'Metal fasteners' },
  { term: 'closures of metal', class: 6, description: 'Metal container parts' },
  { term: 'cobalt raw', class: 6, description: 'Metal materials' },
  { term: 'collars of metal', class: 6, description: 'Metal fasteners' },
  { term: 'common metals unwrought or semi-wrought', class: 6, description: 'Metal materials' },
  { term: 'containers of metal', class: 6, description: 'Metal storage' },
  { term: 'copper rings', class: 6, description: 'Metal rings' },
  { term: 'copper wire', class: 6, description: 'Metal wires' },
  { term: 'cornices of metal', class: 6, description: 'Metal building materials' },
  { term: 'couplings of metal', class: 6, description: 'Metal connectors' },
  { term: 'crash barriers of metal', class: 6, description: 'Metal safety equipment' },
  { term: 'door bells of metal', class: 6, description: 'Metal hardware' },
  { term: 'door bolts of metal', class: 6, description: 'Metal door hardware' },
  { term: 'door closers of metal', class: 6, description: 'Metal door hardware' },
  { term: 'door fasteners of metal', class: 6, description: 'Metal door hardware' },
  { term: 'door frames of metal', class: 6, description: 'Metal building materials' },
  { term: 'door handles of metal', class: 6, description: 'Metal door hardware' },
  { term: 'door knockers of metal', class: 6, description: 'Metal door hardware' },
  { term: 'door panels of metal', class: 6, description: 'Metal building materials' },
  { term: 'door scrapers', class: 6, description: 'Metal door hardware' },
  { term: 'door springs of metal', class: 6, description: 'Metal door hardware' },
  { term: 'door stops of metal', class: 6, description: 'Metal door hardware' },
  { term: 'doors of metal', class: 6, description: 'Metal building materials' },
  { term: 'drain pipes of metal', class: 6, description: 'Metal plumbing materials' },
  { term: 'drain traps of metal', class: 6, description: 'Metal plumbing materials' },
  { term: 'ducts of metal', class: 6, description: 'Metal ventilation materials' },
  { term: 'elbows of metal for pipes', class: 6, description: 'Metal plumbing materials' },
  { term: 'eye bolts', class: 6, description: 'Metal fasteners' },
  { term: 'fences of metal', class: 6, description: 'Metal building materials' },
  { term: 'ferrules of metal', class: 6, description: 'Metal hardware' },
  { term: 'figurines of metal', class: 6, description: 'Metal decorative items' },
  { term: 'fittings of metal for beds', class: 6, description: 'Metal furniture hardware' },
  { term: 'fittings of metal for buildings', class: 6, description: 'Metal building hardware' },
  { term: 'fittings of metal for furniture', class: 6, description: 'Metal furniture hardware' },
  { term: 'fittings of metal for windows', class: 6, description: 'Metal window hardware' },
  { term: 'flanges of metal', class: 6, description: 'Metal pipe fittings' },
  { term: 'flashing of metal', class: 6, description: 'Metal roofing materials' },
  { term: 'floor tiles of metal', class: 6, description: 'Metal flooring materials' },
  { term: 'floors of metal', class: 6, description: 'Metal building materials' },
  { term: 'foils of metal', class: 6, description: 'Metal sheets' },
  { term: 'foot scrapers', class: 6, description: 'Metal hardware' },
  { term: 'frames of metal for building', class: 6, description: 'Metal building materials' },
  { term: 'framework of metal for building', class: 6, description: 'Metal building materials' },
  { term: 'furnace fireguards of metal', class: 6, description: 'Metal safety equipment' },
  { term: 'furniture casters of metal', class: 6, description: 'Metal furniture hardware' },
  { term: 'galena ore', class: 6, description: 'Metal ores' },
  { term: 'gates of metal', class: 6, description: 'Metal building materials' },
  { term: 'german silver', class: 6, description: 'Metal alloys' },
  { term: 'germanium', class: 6, description: 'Metal materials' },
  { term: 'gold solder', class: 6, description: 'Metal soldering materials' },
  { term: 'gratings of metal', class: 6, description: 'Metal building materials' },
  { term: 'greenhouse frames of metal', class: 6, description: 'Metal building materials' },
  { term: 'guard rails of metal', class: 6, description: 'Metal safety equipment' },
  { term: 'gutter pipes of metal', class: 6, description: 'Metal plumbing materials' },
  { term: 'hafnium', class: 6, description: 'Metal materials' },
  { term: 'handcuffs', class: 6, description: 'Metal restraints' },
  { term: 'handling pallets of metal', class: 6, description: 'Metal storage equipment' },
  { term: 'hardware of metal', class: 6, description: 'Metal hardware' },
  { term: 'hinges of metal', class: 6, description: 'Metal hardware' },
  { term: 'hooks of metal', class: 6, description: 'Metal hardware' },
  { term: 'hoppers of metal', class: 6, description: 'Metal containers' },
  { term: 'house numbers of metal', class: 6, description: 'Metal identification items' },
  { term: 'ice moulds of metal', class: 6, description: 'Metal molds' },
  
  // Class 8 - Hand Tools
  { term: 'abrading instruments [hand instruments]', class: 8, description: 'Hand-operated tools' },
  { term: 'adzes [tools]', class: 8, description: 'Woodworking tools' },
  { term: 'agricultural forks', class: 8, description: 'Gardening tools' },
  { term: 'agricultural implements [hand-operated]', class: 8, description: 'Farming tools' },
  { term: 'air pumps [hand-operated]', class: 8, description: 'Inflation tools' },
  { term: 'annular screw plates', class: 8, description: 'Threading tools' },
  { term: 'augers [hand tools]', class: 8, description: 'Drilling tools' },
  { term: 'awls', class: 8, description: 'Piercing tools' },
  { term: 'axes', class: 8, description: 'Cutting tools' },
  { term: 'bayonets', class: 8, description: 'Blade tools' },
  { term: 'beard clippers', class: 8, description: 'Personal grooming tools' },
  { term: 'bench vices', class: 8, description: 'Clamping tools' },
  { term: 'bill-hooks', class: 8, description: 'Cutting tools' },
  { term: 'bits [hand tools]', class: 8, description: 'Drilling tools' },
  { term: 'blade sharpening instruments', class: 8, description: 'Sharpening tools' },
  { term: 'blades [hand tools]', class: 8, description: 'Cutting tools' },
  { term: 'border shears', class: 8, description: 'Gardening tools' },
  { term: 'borers', class: 8, description: 'Drilling tools' },
  { term: 'bow saws', class: 8, description: 'Cutting tools' },
  { term: 'box cutters', class: 8, description: 'Cutting tools' },
  { term: 'braiders [hand tools]', class: 8, description: 'Braiding tools' },
  { term: 'breast drills', class: 8, description: 'Drilling tools' },
  { term: 'budding knives', class: 8, description: 'Gardening tools' },
  { term: 'carpenters augers', class: 8, description: 'Woodworking tools' },
  { term: 'cattle marking tools', class: 8, description: 'Farming tools' },
  { term: 'caulking irons', class: 8, description: 'Sealing tools' },
  { term: 'center punches [hand tools]', class: 8, description: 'Marking tools' },
  { term: 'ceramic knives', class: 8, description: 'Cutting tools' },
  { term: 'cheese slicers [non-electric]', class: 8, description: 'Kitchen tools' },
  { term: 'chisels', class: 8, description: 'Carving tools' },
  { term: 'clamps for carpenters or coopers', class: 8, description: 'Woodworking tools' },
  { term: 'cleavers', class: 8, description: 'Kitchen tools' },
  { term: 'crimping irons', class: 8, description: 'Hair styling tools' },
  { term: 'crow bars', class: 8, description: 'Prying tools' },
  { term: 'curling tongs', class: 8, description: 'Hair styling tools' },
  { term: 'cuticle nippers', class: 8, description: 'Nail care tools' },
  { term: 'cutlery', class: 8, description: 'Kitchen tools' },
  { term: 'cutter bars', class: 8, description: 'Cutting tools' },
  { term: 'cutting tools [hand tools]', class: 8, description: 'Hand-operated tools' },
  { term: 'daggers', class: 8, description: 'Blade tools' },
  { term: 'depilation appliances [electric and non-electric]', class: 8, description: 'Personal grooming tools' },
  { term: 'dies [hand tools]', class: 8, description: 'Threading tools' },
  { term: 'diggers [hand tools]', class: 8, description: 'Gardening tools' },
  { term: 'drawing knives', class: 8, description: 'Woodworking tools' },
  { term: 'drill holders [hand tools]', class: 8, description: 'Drilling tools' },
  { term: 'ear-piercing apparatus', class: 8, description: 'Personal grooming tools' },
  { term: 'earth rammers [hand tools]', class: 8, description: 'Construction tools' },
  { term: 'edge tools [hand tools]', class: 8, description: 'Cutting tools' },
  { term: 'egg slicers [non-electric]', class: 8, description: 'Kitchen tools' },
  { term: 'embossers [hand tools]', class: 8, description: 'Marking tools' },
  { term: 'emery boards', class: 8, description: 'Nail care tools' },
  { term: 'emery files', class: 8, description: 'Filing tools' },
  { term: 'engraving needles', class: 8, description: 'Engraving tools' },
  { term: 'extension pieces for braces for screw taps', class: 8, description: 'Threading tools' },
  { term: 'eyelash curlers', class: 8, description: 'Personal grooming tools' },
  { term: 'farriers knives', class: 8, description: 'Animal care tools' },
  { term: 'files [tools]', class: 8, description: 'Filing tools' },
  { term: 'fingernail polishers [electric or non-electric]', class: 8, description: 'Nail care tools' },
  { term: 'fire irons', class: 8, description: 'Fireplace tools' },
  { term: 'flat irons', class: 8, description: 'Pressing tools' },
  { term: 'fleshing knives', class: 8, description: 'Butcher tools' },
  { term: 'foundry ladles [hand tools]', class: 8, description: 'Metalworking tools' },
  { term: 'frames for handsaws', class: 8, description: 'Cutting tools' },
  { term: 'fruit pickers [hand tools]', class: 8, description: 'Gardening tools' },
  { term: 'garden tools [hand-operated]', class: 8, description: 'Gardening tools' },
  { term: 'gimlets [hand tools]', class: 8, description: 'Drilling tools' },
  { term: 'glaziers diamonds [parts of hand tools]', class: 8, description: 'Glass cutting tools' },
  { term: 'goffering irons', class: 8, description: 'Fabric tools' },
  { term: 'gouges [hand tools]', class: 8, description: 'Carving tools' },
  { term: 'grafting tools', class: 8, description: 'Gardening tools' },
  { term: 'graving tools [hand tools]', class: 8, description: 'Engraving tools' },
  { term: 'grinding wheels [hand tools]', class: 8, description: 'Sharpening tools' },
  { term: 'guns [hand tools]', class: 8, description: 'Hand-operated tools' },
  { term: 'hackles [hand tools]', class: 8, description: 'Textile tools' },
  { term: 'hair clippers for animals [hand instruments]', class: 8, description: 'Animal grooming tools' },
  { term: 'hair clippers for personal use [electric and non-electric]', class: 8, description: 'Personal grooming tools' },
  { term: 'hammer sharpeners', class: 8, description: 'Sharpening tools' },
  { term: 'hammers [hand tools]', class: 8, description: 'Striking tools' },
  { term: 'hand drills [hand tools]', class: 8, description: 'Drilling tools' },
  { term: 'hand implements for hair curling', class: 8, description: 'Hair styling tools' },
  { term: 'hand pumps', class: 8, description: 'Inflation tools' },
  { term: 'hand tools [hand-operated]', class: 8, description: 'Hand-operated tools' },
  { term: 'harpoons', class: 8, description: 'Fishing tools' },
  { term: 'hatchets', class: 8, description: 'Cutting tools' },
  { term: 'hobby knives [scalpels]', class: 8, description: 'Craft tools' },
  { term: 'hoes [hand tools]', class: 8, description: 'Gardening tools' },
  { term: 'holing axes', class: 8, description: 'Woodworking tools' },
  { term: 'hollowing bits [parts of hand tools]', class: 8, description: 'Carving tools' },
  { term: 'hoop cutters [hand tools]', class: 8, description: 'Cutting tools' },
  { term: 'hunting knives', class: 8, description: 'Blade tools' },
  { term: 'ice picks', class: 8, description: 'Ice tools' },
  { term: 'insecticide atomizers [hand tools]', class: 8, description: 'Gardening tools' },
  { term: 'insecticide sprayers [hand tools]', class: 8, description: 'Gardening tools' },
  { term: 'irons [non-electric hand tools]', class: 8, description: 'Pressing tools' },
  { term: 'jig-saws', class: 8, description: 'Cutting tools' },
  { term: 'knife handles', class: 8, description: 'Tool parts' },
  { term: 'knife steels', class: 8, description: 'Sharpening tools' },
  { term: 'knives', class: 8, description: 'Cutting tools' },
  { term: 'ladles [hand tools]', class: 8, description: 'Kitchen tools' },
  { term: 'lawn clippers [hand instruments]', class: 8, description: 'Gardening tools' },
  { term: 'leather strops', class: 8, description: 'Sharpening tools' },
  { term: 'levers', class: 8, description: 'Prying tools' },
  { term: 'lifting jacks [hand-operated]', class: 8, description: 'Lifting tools' },
  { term: 'machetes', class: 8, description: 'Cutting tools' },
  { term: 'mallets [hand instruments]', class: 8, description: 'Striking tools' },
  { term: 'manicure sets', class: 8, description: 'Nail care tools' },
  { term: 'marline spikes', class: 8, description: 'Rope tools' },
  { term: 'masons hammers', class: 8, description: 'Construction tools' },
  { term: 'mattocks', class: 8, description: 'Digging tools' },
  { term: 'milling cutters [hand tools]', class: 8, description: 'Cutting tools' },
  { term: 'mincing knives [hand tools]', class: 8, description: 'Kitchen tools' },
  { term: 'mitre boxes [hand tools]', class: 8, description: 'Woodworking tools' },
  { term: 'molding irons', class: 8, description: 'Metalworking tools' },
  { term: 'mortars for pounding', class: 8, description: 'Kitchen tools' },
  { term: 'mortise axes', class: 8, description: 'Woodworking tools' },
  { term: 'mortise chisels', class: 8, description: 'Woodworking tools' },
];

// Extended descriptions for each Nice class
export const niceClassDescriptions: Record<number, {
  title: string;
  description: string;
  examples: string[];
}> = {
  1: {
    title: 'Chemicals',
    description: 'Chemicals for industry, science and photography',
    examples: ['Industrial chemicals', 'Adhesives', 'Unprocessed resins']
  },
  2: {
    title: 'Paints',
    description: 'Paints, varnishes, lacquers',
    examples: ['Paints', 'Varnishes', 'Anti-rust preparations']
  },
  3: {
    title: 'Cosmetics',
    description: 'Cosmetics and cleaning preparations',
    examples: ['Lipstick', 'Perfumes', 'Soaps', 'Cleaning preparations']
  },
  4: {
    title: 'Industrial Oils',
    description: 'Industrial oils and greases, lubricants, fuels',
    examples: ['Motor oil', 'Fuel', 'Candles', 'Industrial grease']
  },
  5: {
    title: 'Pharmaceuticals',
    description: 'Pharmaceuticals, medical and veterinary preparations',
    examples: ['Medicines', 'Dietary supplements', 'Medical dressings']
  },
  6: {
    title: 'Common Metals',
    description: 'Common metals and their alloys, metal building materials',
    examples: ['Metal pipes', 'Building materials', 'Hardware']
  },
  7: {
    title: 'Machines',
    description: 'Machines, machine tools, motors and engines',
    examples: ['Industrial machines', 'Power tools', 'Agricultural machinery']
  },
  8: {
    title: 'Hand Tools',
    description: 'Hand tools and implements (hand-operated)',
    examples: ['Hammers', 'Screwdrivers', 'Garden tools']
  },
  9: {
    title: 'Electronics',
    description: 'Scientific, research, navigation, and electronic apparatus',
    examples: ['Computers', 'Software', 'Mobile phones', 'Cameras']
  },
  10: {
    title: 'Medical Apparatus',
    description: 'Surgical, medical, dental and veterinary apparatus',
    examples: ['Medical instruments', 'Diagnostic equipment', 'Prosthetics']
  },
  11: {
    title: 'Lighting & Heating',
    description: 'Apparatus for lighting, heating, cooling, and ventilation',
    examples: ['Lamps', 'Air conditioners', 'Water heaters']
  },
  12: {
    title: 'Vehicles',
    description: 'Vehicles and apparatus for transportation',
    examples: ['Cars', 'Bicycles', 'Boats', 'Aircraft']
  },
  13: {
    title: 'Firearms',
    description: 'Firearms, ammunition and projectiles',
    examples: ['Guns', 'Ammunition', 'Explosives']
  },
  14: {
    title: 'Precious Metals',
    description: 'Precious metals, jewelry, precious stones',
    examples: ['Jewelry', 'Watches', 'Precious stones']
  },
  15: {
    title: 'Musical Instruments',
    description: 'Musical instruments and accessories',
    examples: ['Pianos', 'Guitars', 'Musical accessories']
  },
  16: {
    title: 'Paper Goods',
    description: 'Paper, cardboard, printed matter, stationery',
    examples: ['Books', 'Magazines', 'Office supplies']
  },
  17: {
    title: 'Rubber & Plastics',
    description: 'Rubber, plastics, and insulation materials',
    examples: ['Insulation', 'Plastic sheets', 'Rubber seals']
  },
  18: {
    title: 'Leather Goods',
    description: 'Leather, animal skins, luggage, umbrellas',
    examples: ['Bags', 'Wallets', 'Umbrellas']
  },
  19: {
    title: 'Building Materials',
    description: 'Non-metallic building materials',
    examples: ['Wood', 'Stone', 'Cement']
  },
  20: {
    title: 'Furniture',
    description: 'Furniture, mirrors, picture frames',
    examples: ['Tables', 'Chairs', 'Beds', 'Mirrors']
  },
  21: {
    title: 'Household Items',
    description: 'Household or kitchen utensils and containers',
    examples: [
      'Cookware',
      'Tableware',
      'Cleaning implements',
      'Brushes',
      'Glassware',
      'Storage containers',
      'Bathroom accessories',
      'Kitchen utensils'
    ]
  },
  22: {
    title: 'Ropes & Textiles',
    description: 'Ropes, string, nets, tents, awnings',
    examples: ['Ropes', 'Tents', 'Sacks', 'Padding materials']
  },
  23: {
    title: 'Yarns & Threads',
    description: 'Yarns and threads for textile use',
    examples: ['Sewing thread', 'Knitting yarn', 'Embroidery thread']
  },
  24: {
    title: 'Textiles',
    description: 'Textiles and substitutes for textiles',
    examples: ['Fabrics', 'Bed linen', 'Table covers']
  },
  25: {
    title: 'Clothing',
    description: 'Clothing, footwear, headwear',
    examples: ['Shirts', 'Shoes', 'Hats', 'Jackets']
  },
  // ... [continue with remaining classes] ...
};

// Function to find matching classes for a given term
export function findMatchingClasses(term: string): GoodsMapping[] {
  const searchTerm = term.toLowerCase();
  return goodsServicesMapping.filter(item => 
    item.term.toLowerCase().includes(searchTerm) ||
    item.description.toLowerCase().includes(searchTerm)
  );
}

// Function to get related classes based on a given class
export function getRelatedClasses(classNumber: number): number[] {
  // Common related classes
  const relatedClassesMap: Record<number, number[]> = {
    3: [5, 21], // Cosmetics related to pharmaceuticals and brushes/applicators
    9: [42], // Electronics related to software services
    21: [3, 11, 20], // Household items related to cleaning products, appliances, and furniture
    25: [18, 35], // Clothing related to leather goods and retail
    35: [41, 42], // Business services related to education and technology
    41: [35, 42], // Education related to business and technology
    43: [29, 30], // Food services related to food products
  };
  
  return relatedClassesMap[classNumber] || [];
} 