name: Build and Auto-merge
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - feature  # Replace with your branch name

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Create or Update PR
        if: success() && github.event_name == 'push'
        uses: actions/github-script@v7
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.list({
              owner,
              repo,
              head: `${owner}:${context.ref.replace('refs/heads/', '')}`,
              base: 'main',
              state: 'open'
            });
            
            if (result.data.length === 0) {
              await github.rest.pulls.create({
                owner,
                repo,
                head: context.ref.replace('refs/heads/', ''),
                base: 'main',
                title: `Merge ${context.ref.replace('refs/heads/', '')} to main`,
                body: 'Created by GitHub Actions after successful build'
              });
            }
      
      - name: Auto-merge PR
        if: success() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (pr) {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'merge'
              });
            }